//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzeim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibits
    {
        public int ExhibitID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public Nullable<int> Year { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExhibitionID { get; set; }
    
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
